baseURL = 'https://www.matthewgreen.gg'
languageCode = 'en-us'
title = '''Matthew Green's Showcase'''
theme = 'hugo-terminal.css'
[params]
    name = "Matthew Green"
    defaultDescription = "Hello, I am Matthew Green and this is a showcase of all my projects, skills, work experience, and education as well as my contact details."
    defaultKeywords = ["Matthew", "Alan", "Green", "Programmer", "Video", "Game", "Developer", "Unity", "C", "C++", "C#", "Git", "games", "Computer", "Science", "Bachelor's", "Degree", "computers", "software", "VR"]
    
    [params.social]
        email = "dev@matthewgreen.gg"
        github = "greenmatthew"
        linkedin = "matthewalangreen"
        gitea = "https://git.matthewgreen.gg/mgreen"


[main]
    [[menus.main]]
        name = 'About Me'
        pageRef = '#about-me'
        weight = 10

    [[menus.main]]
        name = 'Projects'
        pageRef = '#projects'
        weight = 20

    [[menus.main]]
        name = 'Skills'
        pageRef = '#skills'
        weight = 30

    [[menus.main]]
        name = 'Work Experience'
        pageRef = '#work-experience'
        weight = 40

    [[menus.main]]
        name = 'Education'
        pageRef = '#education'
        weight = 50

    [[menus.main]]
        name = 'Contact'
        pageRef = '#contact'
        weight = 60

[module]
    [module.hugoVersion]
        extended = false
        min = "0.116.0"

[privacy]
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
